### ISSUE TITLE
Take a look at dnlib

### ISSUE THREAD

**Issue by jspraul** [ygoe/CecilExplorer#1]
https://github.com/0xd4d/dnlib

Not sure how much work it would be to support dnlib, which started with a Cecil-ish API.

**Comment by ygoe** [comment]
To be honest I've never looked into dnlib (except once and then it didn't work for me). I'm using Cecil for a number of applications (most recently a Fody add-in) and it's working well there (with a few enhancements in another case). I may take a look at this but it probably won't happen soon.

**Comment by jspraul** [comment]
Thanks for the feedback. Keep up the good work!
